### ISSUE TITLE
Do you know how to fix intersection for method parameter?

### ISSUE THREAD

**Issue by tempuku** [klausweiss/typing-protocol-intersection#11] opened 2024-02-12 17:58 UTC
I want to have proper check for method parameters.
![image](https://github.com/klausweiss/typing-protocol-intersection/assets/54141071/4d7e1218-e97f-42a7-b372-7d4969ae6feb)
There is a chain of methods, one by one.
For the second one we have Builder[Has[T,APR]] as input and Builder[Has[APR]] as type annotation.
But for the third one we have Builder[Has[APR, BPR]] as input and Builder[Has[T, APR]] as type annotation. And it fails!

test.py:156: error: Invalid self argument "Builder[ProtocolIntersection[APR, BPR]]" to attribute function "func3" with type "Callable[[Builder[typing_protocol_intersection.types.ProtocolIntersection​​​​​[T, APR]]], Builder[typing_protocol_intersection.types.ProtocolIntersection​​​​​​[T, DPR]]]"  [misc]
Found 1 error in 1 file (checked 1 source file)

What do I imply: if a type annotation is a subset of an input, then there should not be an error. But it doesnt.

I guess it should work with this line of code:
signature.arg_types = [resolver.fold_intersection_and_its_args(t) for t in signature.arg_types]
but arg_types is always empty...

So I tried to update signature.definition.type and signature.definition.unanalyzed_type with no result.

Maybe you have some assumptions? Is intersection_function_signature_hook method the right one to make changes here?

Thanks a lot for you work,
Aleksandr

**Comment by tempuku** [comment] 2024-02-12 18:03
Don't you mind if we add each other on linkedin? It's not obvious to find you  :)

**Comment by klausweiss** [comment] 2024-02-12 21:39
Hey.  If you provide me with a gist with a minimal reproducible example, I might find some time to look at it in the coming days. Would be best if it also included how you intend to call these methods in the gist.

**Comment by tempuku** [comment] 2024-02-14 08:35
https://gist.github.com/tempuku/df37ab79a89cb2a6cfb60f8df05687af

There is also an update for typing_protocol_intersection/mypy_plugin.py module.

**Comment by klausweiss** [comment] 2024-02-14 20:01
Your example is missing the definition of `T`, I assume you went with `T = TypeVar("T")`.
If you use a covariant type variable it will work with the current plugin version.
```python
T = TypeVar("T", covariant=True)
```

**Comment by tempuku** [comment] 2024-02-15 13:55
It's brilliant, thank you!

Where did you find information about mypy's plugin system under the hood? This chapter in docs are really tiny and offer to "contact the mypy core developers on [gitter](https://gitter.im/python/typing)".
Mb you have any materials on it?

**Comment by klausweiss** [comment] 2024-02-15 19:34
I'm by no means expert in mypy plugins. I don't recall using any specific resources aside from the docs and running mypy with a debugger attached.

Also, I have to say I quite like how in your example the order in which the methods are called is ensured at the type-level.

Closing, since solved.

**Closed by klausweiss** 2024-02-15 19:34 UTC
